module.exports =
    {
        "login": "dlatex",
        "id": 16075123,
        "avatar_url": "https://avatars2.githubusercontent.com/u/16075123?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dlatex",
        "html_url": "https://github.com/dlatex",
        "followers_url": "https://api.github.com/users/dlatex/followers",
        "following_url": "https://api.github.com/users/dlatex/following{/other_user}",
        "gists_url": "https://api.github.com/users/dlatex/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dlatex/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dlatex/subscriptions",
        "organizations_url": "https://api.github.com/users/dlatex/orgs",
        "repos_url": "https://api.github.com/users/dlatex/repos",
        "events_url": "https://api.github.com/users/dlatex/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dlatex/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Delex Lath",
        "company": null,
        "blog": "",
        "location": null,
        "email": null,
        "hireable": null,
        "bio": null,
        "public_repos": 10,
        "public_gists": 0,
        "followers": 0,
        "following": 0,
        "created_at": "2015-11-30T02:13:28Z",
        "updated_at": "2017-12-25T21:58:42Z"
    }